MvcCoreSasStorage/Models/Alumno.cs
using Azure;
using Azure.Data.Tables;

namespace MvcCoreSasStorage.Models
{
    public class Alumno : ITableEntity
    {
        private int _IdAlumno;
        private string _Curso;

        public int IdAlumno
        {
            get { return this._IdAlumno; }
            set {
                this._IdAlumno = value;
                this.RowKey = value.ToString();
            }
        }

        public string Curso
        {
            get { return this._Curso; }
            set {
                this._Curso = value;
                this.PartitionKey = value;
            }
        }

        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int Nota { get; set; }

        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }
    }
}

MvcCoreSasStorage/Models/ErrorViewModel.cs
namespace MvcCoreSasStorage.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreSasStorage/Controllers/AlumnosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreSasStorage.Models;
using MvcCoreSasStorage.Services;

namespace MvcCoreSasStorage.Controllers
{
    public class AlumnosController : Controller
    {
        private ServiceAzureAlumnos service;

        public AlumnosController(ServiceAzureAlumnos service)
        {
            this.service = service;
        }

        public IActionResult Token()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Token(string curso)
        {
            string data = await this.service.GetTokenAsync(curso);
            ViewData["TOKEN"] = data;
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string token)
        {
            List<Alumno> alumnos = 
                await this.service.GetAlumnosAsync(token);
            return View(alumnos);
        }
    }
}

MvcCoreSasStorage/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreSasStorage.Models;
using System.Diagnostics;

namespace MvcCoreSasStorage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreSasStorage/Controllers/MigracionController.cs
using Azure.Data.Tables;
using Microsoft.AspNetCore.Mvc;
using MvcCoreSasStorage.Helpers;
using MvcCoreSasStorage.Models;

namespace MvcCoreSasStorage.Controllers
{
    public class MigracionController : Controller
    {
        private HelperXML helper;

        public MigracionController(HelperXML helper)
        {
            this.helper = helper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string algo)
        {
            string azureKeys =
    "DefaultEndpointsProtocol=https;AccountName=storageaccountpaco;AccountKey=A5IdMIsgAdfHuO46U8QdbruPy0PXfILvLTW29uTxTth7bqOHiOrRuTYCdQrW+OC48J0hO41t059P+AStEBO4mA==;EndpointSuffix=core.windows.net";
            //string azureKeys =
            //    "UseDevelopmentStorage=true";
            TableServiceClient tableServiceClient =
                new TableServiceClient(azureKeys);
            TableClient tableClient =
                tableServiceClient.GetTableClient("alumnos");
            await tableClient.CreateIfNotExistsAsync();
            List<Alumno> alumnos = this.helper.GetAlumnosXML();
            foreach (Alumno alumn in alumnos)
            {
                await tableClient.AddEntityAsync<Alumno>(alumn);
            }
            ViewData["MENSAJE"] = "Migración de alumnos correcta";
            return View();
        }
    }
}

MvcCoreSasStorage/Views/Alumnos/Index.cshtml
@model IEnumerable<MvcCoreSasStorage.Models.Alumno>

@{
    ViewData["Title"] = "Index";
}

<h1>Alumnos</h1>

<form method="post">
    <label>Token: </label>
    <textarea name="token" class="form-control"></textarea>
    <button class="btn btn-info">
        Mostrar alumnos
    </button>
</form>

@if (Model != null)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IdAlumno)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Curso)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellidos)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nota)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdAlumno)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Curso)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellidos)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nota)
                    </td>
                    <td>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreSasStorage/Views/Alumnos/Token.cshtml
<h1 style="color:red">
    Generar Token de Alumnos
</h1>
<form method="post">
    <label>Introduzca curso: </label>
    <input type="text" name="curso" class="form-control"/>
    <button class="btn btn-warning">
        Token
    </button>
</form>

<p>Token generado: </p>
<textarea class="form-control">@ViewData["TOKEN"]</textarea>

MvcCoreSasStorage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreSasStorage/Views/Migracion/Index.cshtml
<h1>Migración de datos Azure Storage Tables</h1>

<form method="post">
    <button class="btn btn-danger">
        Migrar datos XML Azure Storage
    </button>
</form>

<h1 style="color:blue">
    @ViewData["MENSAJE"]
</h1>

MvcCoreSasStorage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreSasStorage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreSasStorage.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreSasStorage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" 
                            asp-controller="Migracion" 
                            asp-action="Index">
                                Migración Alumnos Azure
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-sucess"
                            asp-controller="Alumnos" 
                            asp-action="Token">
                                Token
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info"
                               asp-controller="Alumnos"
                               asp-action="Index">
                                Alumnos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCoreSasStorage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>